%YAML:1.0
Learning:
   learning_rate: 1e-4
   interpolation_factor: 0.02
   cell_size: 4
Scale:
   scale_step: 1.1
   pyramid_levels: 5
   use_scale: 0
   subgrid_scale: 0
   scale_momentum: 1.10
Localization:
   resize_image: 0
   subpixel_localization: 1
Redetection:
   update_template: 1
   detect_lost_target: 0
   update_threshold: 10.0
   detection_threshold: 3.0
   box_proposals: 15
   generate_max_boxes: 0
RegressionNet:
   use_regression_net: 0
